name: chess_game
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  stockfish_for_flutter:
    path: ./plugins/stockfish_for_flutter
  cupertino_icons: ^1.0.8
  chess: ^0.8.1
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/capture.mp3
    - assets/sounds/move-check.mp3
    - assets/stockfish/
    - assets/icons/                            



